dubbo:
  protocol:
    name: dubbo
    port: 20881
  application:
    name: test-opensource-consumer
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  registry:
    id: zk-registry
    address: zookeeper://47.96.149.30:2181?timeout=20000
  config-center:
    address: zookeeper://47.96.149.30:2181?timeout=20000
  metadata-report:
    address: zookeeper://47.96.149.30:2181?timeout=20000
  consumer:
    timeout: 300000