dubbo:
  application:
    name: test-opensource-consumer
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://47.96.149.30:2181?timeout=20000
  consumer:
    timeout: 300000